### ISSUE TITLE
Cannot find module '/Users/brage/Kode/flexisoft/portal-api/.yarn/releases/yarn-3.4.1.cjs'

### ISSUE THREAD

**Issue by braaar** [bjerkio/create-bjerk-typescript#238] opened 2023-03-09 09:52 UTC
I ran `yarn create bjerk-typescript my-app` and tried to install with `yarn install`

```
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module '/Users/brage/Kode/flexisoft/portal-api/.yarn/releases/yarn-3.4.1.cjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.12.0
```

**Comment by cobraz** [comment] 2023-03-09 10:02
According to offline talks, this was caused by moving the files but `.yarn` wasn't copied.

Closing for now, let me know if there's more issues

**Closed as completed by cobraz** 2023-03-09 10:02 UTC
